---
- hosts: tomcat-cluster

  roles:
    - role: add_user
      config:
        name: tomcat
        primary_group: tomcat
        id: 1000
        group_id: 1000
        priviliges:
          - "ALL=(ALL) NOPASSWD: ALL"

    - role: deploy_to_tomcat
      uri: "{{deploy_uri}}"
      artifact_path: "{{artifact_path}}"
      deployer: "{{deployer}}"
      deployer_password: "{{deployer_password}}"
      tags: ['deploy']
