---
# I suspect a loop should be used there
# as an iterable there should be tomcat-cluster group
# at each iterate we exclude cluster from apache (againt httpd)
# uplodad the artifact into tomcat node and then adding node to the loadbalancer
# again
# https://docs.ansible.com/ansible/2.6/user_guide/playbooks_blocks.html#error-handling
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#rolling-update-batch-size
# https://docs.ansible.com/ansible/2.6/scenario_guides/guide_rolling_upgrade.html
# TODO: test if tomcat instance can be excluded from vhosts.conf
- hosts: tomcat-cluster
  serial: 1

  pre_tasks:
    - name: Configure tomcat user
      include_role:
        name: add_user
      vars:
        config:
          name: tomcat
          primary_group: tomcat
          id: 1000
          group_id: 1000
          priviliges:
            - "ALL=(ALL) NOPASSWD: ALL"
    - name: Exclude node to deploy from LB
      include_role:
        name: httpd
        tasks_from: exclude_node
      vars:
        node_hostname: "{{inventory_hostname}}"
      delegate_to: "{{item}}"
      with_items: groups.webservers

  tasks:
    - name: Proceed rolling update
      block:
        - include_role:
            name: deploy_to_tomcat
          vars:
            uri: "{{deploy_uri}}"
            artifact_path: "{{artifact_path}}"
            deployer: "{{deployer}}"
            deployer_password: "{{deployer_password}}"
          become: true
          become_user: tomcat
      rescue:
        - include_role:
            name: httpd
            tasks_from: exclude_node
          vars:
            node_hostname: "{{inventory_hostname}}"
          delegate_to: "{{item}}"
          with_items: groups.webservers

# - name: If deployed to more than 50% nodes, replase old nodes from LB with new
