---
- name: Change owner of directory
  file:
    path: "{{ansible_env.CATALINA_HOME}}"
    recurse: true
    owner: tomcat
    group: tomcat
    state: directory
  become: true

# - name: Proceed healthcheck

- name: Exclude node to deploy from LB
  include_role:
    name: httpd
    tasks_from: exclude_node
  vars:
    node_hostname: "{{inventory_hostname}}"

- name: Check is artifact deployed
  stat:
    path: "{{ansible_env.CATALINA_HOME}}/webapps/{{artifact_name}}"
  register: artifact_stat_result

- name: Backup previous version
  copy:
    src: "{{ansible_env.CATALINA_HOME}}/webapps/{{artifact_name}}"
    remote_src: true
    dest: "{{ansible_env.CATALINA_HOME}}/webapps/{{artifact_name}}.bkp"
    owner: tomcat
    group: tomcat
    mode: 0644
  when: artifact_stat_result.stat.exists

- name: Copy artifact to remote
  copy:
    src: "{{artifact_path}}"
    dest: "/tmp/{{artifact_name}}"
    owner: tomcat
    group: tomcat
    mode: 0644

- name: Ensure curl is installed
  package:
    state: present
    name: curl

- name: Download artifact to tomcat manager
  command: >-
    /usr/bin/curl --user {{deployer}}:{{deployer_password}}
    --upload-file /tmp/{{artifact_name}}
    http://localhost:{{tomcat_port}}/manager/text/deploy?path=/{{deploy_uri}}
  register: deploy_output
  warn: false

# - name: Check is artifact deployed

- name: Add node to loadbalancer
  include_role:
    name: httpd
    tasks_from: include_node
  vars:
    node_hostname: "{{inventory_hostname}}"


# - name: If deployed to more than 50% nodes, replase old nodes from LB with new
