---
- name: Change owner of directory
  file:
    path: "{{q('env', 'CATALINA_HOME')}}"
    recurse: true
    owner: tomcat
    group: tomcat
    state: directory
  become: true

# - name: Proceed healthcheck

# - name: Exclude node to deploy from LB

- name: Copy new artifact to destination
  copy:
    src: "{{artifact_path}}"
    dest: "{{artifact_destination}}"
    owner: root
    group: root
    mode: 0644

# - name: Check is artifact deployed

# - name: Add node to loadbalancer

# - name: If deployed to more than 50% nodes, replase old nodes from LB with new
