---
- name: Get hash of new artifact
  local_action:
    module: stat
    path: "{{artifact_path}}"
    checksum: md5
  register: new
  failed_when: new.stat.exists == False
  become: false

- name: Get hash of currently deployed artifact
  stat:
    path: "{{artifact_destination}}"
    checksum: md5
  register: deployed
  failed_when:
    - deployed.stat.checksum is defined
    - new.stat.checksum == deployed.stat.checksum

- name: Copy new artifact to destination
  copy:
    src: "{{artifact_path}}"
    dest: "{{artifact_destination}}"
    # TODO: add tomcat user to each tomcat cotnainer and update this role
    owner: root
    group: root
    mode: 0644
